import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import hashtagsRouter from "./hashtags";
import discoveryRouter from "./discovery";
import conversationsRouter from "./conversations";
import messagesRouter from "./messages";
import roomsRouter from "./rooms";
import statsRouter from "./stats";
import friendsRouter from "./friends";
import adminRouter from "./admin";
import mvpRouter from "./mvp";
import reelsRouter from "./reels";
import storageRouter from "./storage";
import photosRouter from "./photos";
import callsRouter from "./calls";
import postsRouter from "./posts";
import pollsRouter from "./polls";
import linkPreviewRouter from "./linkPreview";
import socialRouter from "./social";
import gifsRouter from "./gifs";
import notificationsRouter from "./notifications";
import eventsRouter from "./events";
import communitiesRouter from "./communities";
import premiumRouter from "./premium";
import searchRouter from "./search";
import bookmarksRouter from "./bookmarks";
import preferencesRouter from "./preferences";
import pushRouter from "./push";

const router: IRouter = Router();

router.use(healthRouter);
// friendsRouter must be registered BEFORE usersRouter so its specific
// /users/lookup and /users/by-code/:code routes win over /users/:id.
router.use(friendsRouter);
router.use(usersRouter);
router.use(hashtagsRouter);
router.use(discoveryRouter);
router.use(conversationsRouter);
router.use(messagesRouter);
router.use(roomsRouter);
router.use(statsRouter);
router.use(adminRouter);
router.use(mvpRouter);
router.use(reelsRouter);
router.use(storageRouter);
router.use(photosRouter);
router.use(callsRouter);
router.use(postsRouter);
router.use(pollsRouter);
router.use(linkPreviewRouter);
router.use(socialRouter);
router.use(gifsRouter);
router.use(notificationsRouter);
router.use(eventsRouter);
router.use(communitiesRouter);
router.use(premiumRouter);
router.use(searchRouter);
router.use(bookmarksRouter);
router.use(preferencesRouter);
router.use(pushRouter);

export default router;
