import { Router, type IRouter } from "express";
import healthRouter from "./health";
import usersRouter from "./users";
import hashtagsRouter from "./hashtags";
import discoveryRouter from "./discovery";
import conversationsRouter from "./conversations";
import messagesRouter from "./messages";
import roomsRouter from "./rooms";
import statsRouter from "./stats";
import friendsRouter from "./friends";
import adminRouter from "./admin";
import mvpRouter from "./mvp";
import reelsRouter from "./reels";
import storageRouter from "./storage";
import photosRouter from "./photos";
import callsRouter from "./calls";
import postsRouter from "./posts";
import pollsRouter from "./polls";
import linkPreviewRouter from "./linkPreview";
import socialRouter from "./social";
import gifsRouter from "./gifs";
import notificationsRouter from "./notifications";
import eventsRouter from "./events";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(hashtagsRouter);
router.use(discoveryRouter);
router.use(conversationsRouter);
router.use(messagesRouter);
router.use(roomsRouter);
router.use(statsRouter);
router.use(friendsRouter);
router.use(adminRouter);
router.use(mvpRouter);
router.use(reelsRouter);
router.use(storageRouter);
router.use(photosRouter);
router.use(callsRouter);
router.use(postsRouter);
router.use(pollsRouter);
router.use(linkPreviewRouter);
router.use(socialRouter);
router.use(gifsRouter);
router.use(notificationsRouter);
router.use(eventsRouter);

export default router;
